import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function GET() {
    try {
        // defined path to the simulation output
        // In a real app, this would be a DB query or identifying the latest file.
        // For this checkpoint, we target the specific simulation output.
        // DYNAMIC PATH RESOLUTION:
        // Priority 1: Docker/Production Mount (/app/reports)
        // Priority 2: Local Dev Relative Path
        let reportPath = '/app/reports/report_sim_universal_user_001.md';

        if (!fs.existsSync(reportPath)) {
            reportPath = path.resolve(process.cwd(), '../../03_Reporter_Cluster/output/report_sim_universal_user_001.md');
        }

        if (!fs.existsSync(reportPath)) {
            return NextResponse.json(
                { error: 'Report not found. Please run the simulation first.' },
                { status: 404 }
            );
        }

        const markdown = fs.readFileSync(reportPath, 'utf8');

        // Simple Markdown to HTML Conversion
        // This is a "Skeleton" implementation to avoid adding heavy dependencies like 'marked' or 'remark' just yet.
        // It handles the basic structure generated by the AI: Headers (H1-H4), Bold, lists, and paragraphs.
        let html = markdown
            // Headers
            .replace(/^### (.*$)/gim, '<h3>$1</h3>')
            .replace(/^## (.*$)/gim, '<h2>$1</h2>')
            .replace(/^# (.*$)/gim, '<h1>$1</h1>')
            .replace(/^#### (.*$)/gim, '<h4>$1</h4>')
            // Bold
            .replace(/\*\*(.*)\*\*/gim, '<b>$1</b>')
            // Italic
            .replace(/\*(.*)\*/gim, '<i>$1</i>')
            // Blockquotes
            .replace(/^\> (.*$)/gim, '<blockquote>$1</blockquote>')
            // Lists (Basic - assumes single line items for now)
            .replace(/^\* (.*$)/gim, '<ul><li>$1</li></ul>') // Naive, but works for visual verification if valid HTML
            // Fix naive list (remove double ul nesting if any) - simplistic approach:
            // A better approach for Tiptap is just ensuring paragraphs and breaks are clean.
            // Paragraphs (double newlines)
            .replace(/\n\n/gim, '<p></p>');

        // Tiptap expects HTML content.
        return NextResponse.json({ html });

    } catch (error) {
        console.error('Error reading report:', error);
        return NextResponse.json(
            { error: 'Failed to load report.' },
            { status: 500 }
        );
    }
}
